# Generated by Django 3.0.5 on 2020-05-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='title',
            field=models.CharField(default='About Me', max_length=255),
        ),
    ]
