# Generated by Django 3.0.5 on 2020-05-13 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Creative', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Creative',
            },
        ),
        migrations.CreateModel(
            name='OSAPChangesCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Osap Changes Campaign', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'OSAP Changes Campaign',
            },
        ),
        migrations.CreateModel(
            name='RyersonEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('event_date', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Ryerson Events',
            },
        ),
        migrations.CreateModel(
            name='TCEModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='TCE', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'TCE',
            },
        ),
        migrations.CreateModel(
            name='TCEImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/photography/events/tce/')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='photography.TCEModel')),
            ],
        ),
        migrations.CreateModel(
            name='RyersonEventImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/photography/events/ryerson-events/')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='photography.RyersonEvent')),
            ],
        ),
        migrations.CreateModel(
            name='OSAPChangesCampaignImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/photography/events/osap-changes-campaign/')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='photography.OSAPChangesCampaign')),
            ],
        ),
        migrations.CreateModel(
            name='CreativeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/photography/creative/')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='photography.Creative')),
            ],
        ),
    ]
