# Generated by Django 3.0.5 on 2020-05-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ryersonevent',
            name='event_date',
            field=models.DateField(),
        ),
    ]
