# Generated by Django 3.0.8 on 2020-08-04 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0002_auto_20200518_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osapchangescampaignimage',
            name='post',
        ),
        migrations.DeleteModel(
            name='OSAPChangesCampaign',
        ),
        migrations.DeleteModel(
            name='OSAPChangesCampaignImage',
        ),
    ]
