# Generated by Django 3.0.8 on 2020-08-10 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0003_auto_20200804_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creative',
            old_name='title',
            new_name='project_title',
        ),
    ]
