# Generated by Django 3.0.8 on 2020-08-10 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0004_auto_20200810_1803'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreativeImage',
            new_name='ProjectImage',
        ),
    ]
