# Generated by Django 3.0.8 on 2020-08-10 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0005_auto_20200810_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='creative',
            name='project_thumbnail',
            field=models.ImageField(default=None, upload_to='images/photography/creative/'),
        ),
        migrations.AlterField(
            model_name='creative',
            name='project_title',
            field=models.CharField(max_length=255),
        ),
    ]
