# Generated by Django 3.0.8 on 2020-08-10 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0006_auto_20200810_1810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creative',
            options={'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to='images/photography/creative/projects//'),
        ),
    ]
