# Generated by Django 3.0.8 on 2020-08-10 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0007_auto_20200810_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to='images/photography/creative/projects/'),
        ),
    ]
