# Generated by Django 3.0.8 on 2020-08-11 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0009_auto_20200811_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creative',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
