# Generated by Django 3.0.8 on 2020-08-12 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0010_auto_20200811_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creative',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
