# Generated by Django 3.0.5 on 2020-05-07 21:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.FileField(null=True, upload_to='video/', verbose_name='')),
                ('date_uploaded', models.DateField(default=datetime.date.today, verbose_name='Date Uploaded')),
            ],
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
