# Generated by Django 3.0.5 on 2020-05-07 21:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_auto_20200507_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='date_uploaded',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Date Uploaded'),
        ),
    ]
