# Generated by Django 3.0.5 on 2020-05-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0004_auto_20200507_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='date_uploaded',
        ),
        migrations.AddField(
            model_name='movie',
            name='video_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
