# Generated by Django 3.0.5 on 2020-05-07 21:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0005_auto_20200507_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='video_title',
            new_name='movie_title',
        ),
        migrations.AddField(
            model_name='movie',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Date Uploaded'),
        ),
    ]
