# Generated by Django 3.0.5 on 2020-05-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0006_auto_20200507_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie',
            field=models.FileField(null=True, upload_to='videos/', verbose_name=''),
        ),
    ]
