# Generated by Django 3.0.5 on 2020-05-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0009_auto_20200518_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
